### ISSUE TITLE
Add Elastic Search Container + Configs

### ISSUE THREAD

**Issue by bryanlittlefield** [bryanlittlefield/TUGBOAT#82]
**docker-compose.yml** 

```
    elasticsearch:
        image: elasticsearch:7.10.1
        container_name: elasticsearch
        environment:
          - xpack.security.enabled=false
          - discovery.type=single-node
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
        cap_add:
          - IPC_LOCK
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data
          - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
            - "9200:9200"
            - "9300:9300"
```

**elasticsearch/elasticsearch.yml**
```
cluster.name: "docker-cluster"
network.host: elasticsearch
```

---

**Know Issue with Indexing Larger Elastic Search DB's:**

- [ ] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144] : https://stackoverflow.com/questions/51445846/elasticsearch-max-virtual-memory-areas-vm-max-map-count-65530-is-too-low-inc
